import '@/styles/globals.css';
import PieDePagina from "@/components/pieDePagina";
import Encabezado from "@/components/Encabezado";
import Nav from '@/components/Nav';



export const metadata = {
  title: "Bytes Informatica",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body>
        <Encabezado/> 
        <Nav/>
        
        <main>
        {children}

        </main>

<PieDePagina/>
      </body>
    </html>
  );
}
